# Generated by Django 3.2 on 2021-04-27 18:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(help_text="Do not enter any data here. This is an autopopulate fiels from 'Brand Name' field.", unique=True)),
                ('company_bio', models.TextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, help_text='Brand image. WxH => 800x600', null=True, upload_to='images/brands/')),
                ('logo', models.ImageField(blank=True, help_text='All Pages, Partner 1 Logo at "Our Experts". WxH => 113x49', null=True, upload_to='images/brands/')),
                ('logo_hover', models.ImageField(blank=True, help_text='All Pages, Partner 1 Logo (hover in red) at "Our Experts". WxH => 113x49', null=True, upload_to='images/brands/')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(help_text="Do not enter any data here. This is an autopopulate fiels from 'Category Name' field.", unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Customer name.', max_length=100)),
                ('slug', models.SlugField(help_text='Do not enter any data here. This is an autopopulate fiels from "Customer Name" field.', unique=True)),
                ('testimonial', models.TextField(blank=True, max_length=2000)),
                ('image_1', models.ImageField(blank=True, help_text='Customer picture', null=True, upload_to='images/customers')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Home Pages, Expert number name at "Our Experts"', max_length=100, null=True)),
                ('position', models.CharField(blank=True, help_text='Home Pages, Expert number position at PANY company at "Our Experts"', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='Home Pages, Expert number E-mail address at PANY company at "Our Experts"', max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Home Pages, Expert number Phone number at PANY company at "Our Experts"', max_length=128, null=True, region=None)),
                ('image', models.ImageField(blank=True, help_text='Home Pages, Expert number Image at "Our Experts". WxH => 270x270 a sequare size is recommended.', null=True, upload_to='images/themes/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name.', max_length=250)),
                ('features', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(help_text='Do not enter any data here. This is an autopopulate fiels from "Product Name" field.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the Product.', max_length=1000)),
                ('image_1', models.ImageField(blank=True, help_text='1st image', null=True, upload_to='images/products')),
                ('image_2', models.ImageField(blank=True, help_text='2nd image', null=True, upload_to='images/products')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('order', models.IntegerField(help_text='Ordering product view, from lowest to highest.', null=True)),
                ('packaging', models.CharField(blank=True, default='kg', help_text='Enter the package weight.', max_length=10, null=True)),
                ('technical_manual', models.FileField(blank=True, null=True, upload_to='manuals/products')),
                ('product_manual', models.FileField(blank=True, null=True, upload_to='manuals/products')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='website.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.category')),
            ],
            options={
                'ordering': ('-order',),
            },
        ),
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Contact us Page, Sale Point's name", max_length=100, null=True)),
                ('address', models.CharField(blank=True, help_text="Contact us Page, Sale Point's address", max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text="Contact us Page, Sale Point's city", max_length=100, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Contact us Page, Sale Point's Phone Number", max_length=128, null=True, region=None)),
                ('email', models.EmailField(help_text="Contact us Page, Sale Point's E-mail Address", max_length=254)),
                ('active', models.BooleanField(default=True, help_text='Contact us Page, Only the active ones will be shown to the visitors')),
            ],
            options={
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('theme_1', 'Theme_1'), ('theme_2', 'Theme_2'), ('theme_3', 'Theme_3'), ('theme_4', 'Theme_4'), ('theme_5', 'Theme_5'), ('theme_6', 'Theme_6'), ('theme_7', 'Theme_7'), ('theme_8', 'Theme_8'), ('theme_9', 'Theme_9'), ('theme_10', 'Theme_10')], default='', max_length=10, null=True)),
                ('default_theme', models.BooleanField(default=False)),
                ('pany_logo', models.ImageField(blank=True, help_text="All the Pages, PANY Co. Logo. WxH => WxH (doesn't matters as long as the size is less than 100KB)", null=True, upload_to='images/themes/')),
                ('pany_logo_retina', models.ImageField(blank=True, help_text='All the Pages, PANY Co. Logo_2x ... 4x or Retina (higher pixel density) screens Logo. WxH => 2-4x(pany_logo)', null=True, upload_to='images/themes/')),
                ('header_background_brand', models.ImageField(blank=True, help_text='Brand_list & Brand_detail Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/')),
                ('header_background_category', models.ImageField(blank=True, help_text='Category_list & Category_detail Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/')),
                ('header_background_project', models.ImageField(blank=True, help_text='Project_list & Project_detail Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/')),
                ('header_background_product', models.ImageField(blank=True, help_text='Product_list & Product_detail Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/')),
                ('header_background_about_us', models.ImageField(blank=True, help_text='About_us_list & About_us_detail Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/')),
                ('header_background_contact_us', models.ImageField(blank=True, help_text='Contact_us_list & Contact_us_detail Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/')),
                ('slyder_image_1', models.ImageField(blank=True, help_text='Home Page, Slyder 1 image. WxH => 1920x850', null=True, upload_to='images/themes/')),
                ('slyder_title_1', models.CharField(blank=True, help_text='Home Page, Slyder 1 Title.', max_length=100, null=True)),
                ('slyder_text_1', models.CharField(blank=True, help_text='Home Page, Slyder 1 Text.', max_length=200, null=True)),
                ('slyder_image_2', models.ImageField(blank=True, help_text='Home Page, Slyder 2 image. WxH => 1920x850', null=True, upload_to='images/themes/')),
                ('slyder_title_2', models.CharField(blank=True, help_text='Home Page, Slyder 2 Title.', max_length=100, null=True)),
                ('slyder_text_2', models.CharField(blank=True, help_text='Home Page, Slyder 2 Text.', max_length=200, null=True)),
                ('slyder_image_3', models.ImageField(blank=True, help_text='Home Page, Slyder 3 image. WxH => 1920x850', null=True, upload_to='images/themes/')),
                ('slyder_title_3', models.CharField(blank=True, help_text='Home Page, Slyder 3 Title.', max_length=100, null=True)),
                ('slyder_text_3', models.CharField(blank=True, help_text='Home Page, Slyder 3 Text.', max_length=200, null=True)),
                ('slyder_image_4', models.ImageField(blank=True, help_text='Home Page, Slyder 4 image. WxH => 1920x850', null=True, upload_to='images/themes/')),
                ('slyder_title_4', models.CharField(blank=True, help_text='Home Page, Slyder 4 Title.', max_length=100, null=True)),
                ('slyder_text_4', models.CharField(blank=True, help_text='Home Page, Slyder 4 Text.', max_length=200, null=True)),
                ('slyder_image_5', models.ImageField(blank=True, help_text='Home Page, Slyder 5 image. WxH => 1920x850', null=True, upload_to='images/themes/')),
                ('slyder_title_5', models.CharField(blank=True, help_text='Home Page, Slyder 5 Title.', max_length=100, null=True)),
                ('slyder_text_5', models.CharField(blank=True, help_text='Home Page, Slyder 5 Text.', max_length=200, null=True)),
                ('slyder_image_6', models.ImageField(blank=True, help_text='Home Page, Slyder 6 image. WxH => 1920x850', null=True, upload_to='images/themes/')),
                ('slyder_title_6', models.CharField(blank=True, help_text='Home Page, Slyder 6 Title.', max_length=100, null=True)),
                ('slyder_text_6', models.CharField(blank=True, help_text='Home Page, Slyder 6 Text.', max_length=200, null=True)),
                ('quote_title', models.CharField(blank=True, help_text='Home Page, Title at "GET A QUOTE"', max_length=100)),
                ('quote_text', models.CharField(blank=True, help_text='Home Page, Text at "GET A QUOTE"', max_length=100)),
                ('intro_title', models.CharField(blank=True, help_text='Home Page, Title at "Count up introduction"', max_length=100)),
                ('intro_description', models.TextField(blank=True, help_text='Home Page, Description at "Count up introduction"')),
                ('sale_points', models.IntegerField(blank=True, help_text='Home Page, Number of Sale Points (Showroom) at "Count up introduction"', null=True)),
                ('products', models.IntegerField(blank=True, help_text='Home Page, Number of Happy Products at "Count up introduction"', null=True)),
                ('trucks_per_year', models.IntegerField(blank=True, help_text='Home Page, Number of Trucks/Year at "Count up introduction"', null=True)),
                ('projects_supplied', models.IntegerField(blank=True, help_text='Home Page, Number of Projects Supplied at "Count up introduction"', null=True)),
                ('experience_years', models.IntegerField(blank=True, help_text='Home Page, Number of Experience Years at "Count up introduction"', null=True)),
                ('experience_years_image', models.ImageField(blank=True, help_text='Home Page, Image at "Count up introduction". WxH => 270x360 is recommended.', null=True, upload_to='images/themes/')),
                ('about_us_text', models.TextField(blank=True, help_text='Home & about-us Pages, Text at "ABOUT USE"')),
                ('about_us_signature', models.ImageField(blank=True, help_text='Home & about-us Pages, Signature at "ABOUT USE". WxH => 106x59 png transparent background.', null=True, upload_to='images/themes/')),
                ('about_us_name', models.CharField(blank=True, help_text='Home & about-us Pages, Name of the person at "ABOUT USE"', max_length=100)),
                ('about_us_position', models.CharField(blank=True, help_text='Home & about-us Pages, Position of the person at "ABOUT USE"', max_length=100)),
                ('about_us_image', models.ImageField(blank=True, help_text='Home & about-us Pages, Image at "ABOUT USE". WxH => YYYxYYY a sequare size is recommended.', null=True, upload_to='images/themes/')),
                ('our_category_text', models.TextField(blank=True, help_text='Home Page, Text at "OUR CATEGORY"')),
                ('why_choose_use_1_title', models.CharField(blank=True, help_text='Home Page, Section 1 - Title at "Why Choose Us"', max_length=100)),
                ('why_choose_use_1_text', models.CharField(blank=True, help_text='Home Page, Section 1 - Text at "Why Choose Us"', max_length=200)),
                ('why_choose_use_2_title', models.CharField(blank=True, help_text='Home Page, Section 2 - Title at "Why Choose Us"', max_length=100)),
                ('why_choose_use_2_text', models.CharField(blank=True, help_text='Home Page, Section 2 - Text at "Why Choose Us"', max_length=200)),
                ('why_choose_use_3_title', models.CharField(blank=True, help_text='Home Page, Section 3 - Title at "Why Choose Us"', max_length=100)),
                ('why_choose_use_3_text', models.CharField(blank=True, help_text='Home Page, Section 3 - Text at "Why Choose Us"', max_length=200)),
                ('why_choose_use_image', models.ImageField(blank=True, help_text='Home Pages, Image at "Why Choose Us". WxH => 570x370', null=True, upload_to='images/themes/')),
                ('background_categories', models.ImageField(blank=True, help_text='Contact_us & home pages, form background Pages background image. WxH => 960x536', null=True, upload_to='images/themes/')),
                ('background_contact_us', models.ImageField(blank=True, help_text='Contact_us & home pages, form background Pages background image. WxH => 960x600', null=True, upload_to='images/themes/')),
                ('footer_image', models.ImageField(blank=True, help_text='All Pages, Image for Footer background. WxH => 1920x366', null=True, upload_to='images/themes/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Project name', max_length=100)),
                ('slug', models.SlugField(help_text='Do not enter any data here. This is an autopopulate fiels from "Project Name" field.', unique=True)),
                ('challenge', models.TextField(blank=True, help_text="What was the Client's Challenge.", max_length=2000)),
                ('description_1', models.TextField(blank=True, help_text='Description for before the category was applied.', max_length=2000)),
                ('description_2', models.TextField(blank=True, help_text='Description for after the category was applied.', max_length=2000)),
                ('image_1', models.ImageField(blank=True, help_text='Project picture, for project-list page. WxH => 370x300', null=True, upload_to='images/projects')),
                ('image_2', models.ImageField(blank=True, help_text='Project picture, before category was applied. WxH => 770x530', null=True, upload_to='images/projects')),
                ('image_3', models.ImageField(blank=True, help_text='Project picture, after the category was applied, for project-detail page. WxH => 770x530', null=True, upload_to='images/projects')),
                ('order', models.IntegerField(help_text='Ordering project view, from lowest to highest.', null=True)),
                ('category', models.ManyToManyField(help_text='The type of categories used in this project.', max_length=100, related_name='categories', to='website.Category')),
                ('products', models.ManyToManyField(help_text='The type of product(s) used in this project.', max_length=100, to='website.Product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
