# Generated by Django 3.2 on 2021-04-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packaging',
        ),
    ]
