# Generated by Django 3.2 on 2021-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_product_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, help_text='Enter the package weight.', max_length=10, null=True),
        ),
    ]
