# Generated by Django 3.2 on 2021-04-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_manual',
            field=models.FileField(blank=True, default=' KG', null=True, upload_to='manuals/products'),
        ),
    ]
