# Generated by Django 3.2 on 2021-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210504_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slyder_image_7',
            field=models.ImageField(blank=True, help_text='Home Page, Slyder 7 image. WxH => 1920x850', null=True, upload_to='images/themes/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='slyder_image_8',
            field=models.ImageField(blank=True, help_text='Home Page, Slyder 8 image. WxH => 1920x850', null=True, upload_to='images/themes/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='slyder_text_7',
            field=models.CharField(blank=True, help_text='Home Page, Slyder 7 Text.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slyder_text_8',
            field=models.CharField(blank=True, help_text='Home Page, Slyder 8 Text.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slyder_title_7',
            field=models.CharField(blank=True, help_text='Home Page, Slyder 7 Title.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='slyder_title_8',
            field=models.CharField(blank=True, help_text='Home Page, Slyder 8 Title.', max_length=100, null=True),
        ),
    ]
