# Generated by Django 3.2 on 2021-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210505_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Category picture. WxH => 370x300', null=True, upload_to='images/categories'),
        ),
    ]
