# Generated by Django 3.2 on 2021-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_category_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text="Do not enter any data here. This is an autopopulate field from 'Category Name' field.", unique=True),
        ),
    ]
