# Generated by Django 3.2 on 2022-10-29 11:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Description of the Product.', max_length=1000),
        ),
    ]
