# Generated by Django 3.2 on 2022-10-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the Product. you can use </br> between lines to make the the line appear in the next line.', max_length=1000),
        ),
    ]
