# Generated by Django 3.2 on 2022-10-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='roll_length',
            new_name='shelf_life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='roll_width',
        ),
    ]
