# Generated by Django 3.2 on 2022-10-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20221030_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image_3',
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, help_text='Project city.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Project picture (the main picture), for project-list page. WxH => 370x300', null=True, upload_to='images/projects'),
        ),
    ]
