# Generated by Django 3.2 on 2022-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20221030_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, choices=[('duhok', 'Duhok'), ('erbil', 'Erbil'), ('musil', 'Musil'), ('sulaimanya', 'Sulaimanya'), ('duhok', 'Duhok'), ('halabja', 'Halabja'), ('kerkuk', 'Kerkuk'), ('salahaddin', 'Salahaddin'), ('diyala', 'Diyala'), ('baghdad', 'Baghdad'), ('anbar', 'Anbar'), ('karbala', 'Karbala'), ('babil', 'Babil'), ('wasit', 'Wasit'), ('qadisyah', 'Qadisyah'), ('najaf', 'Najaf'), ('maysan', 'Maysan'), ('thiqar', 'Thiqar'), ('muthana', 'Muthana'), ('basra', 'Basra')], help_text='Project city.', max_length=20),
        ),
    ]
