# Generated by Django 3.2 on 2022-12-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_project_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='header_background_document',
            field=models.ImageField(blank=True, help_text='Document_list Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/'),
        ),
    ]
