# Generated by Django 4.2.8 on 2024-01-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_theme_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='header_background_blog',
            field=models.ImageField(blank=True, help_text='Blog_list Pages, Header background image. WxH => 1920x366', null=True, upload_to='images/themes/'),
        ),
    ]
